language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t millsmcilroy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true millsmcilroy/docker-react npm run test